import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';

const roles = [
  { key: 'ADMIN', label: 'Admin', summary: 'Govern platform governance, approvals, and cross-program reporting.' },
  { key: 'PROJECT_MANAGER', label: 'Project Manager', summary: 'Monitor interventions, verify expenses, and manage student progress.' },
  { key: 'TEACHER', label: 'Teacher', summary: 'Update attendance, academic records, and escalate student risks.' },
  { key: 'STUDENT', label: 'Student', summary: 'Track scholarship support, submit expenses, and review learning progress.' },
  { key: 'FUNDER', label: 'CSR Funder', summary: 'Review utilization, transparency, and impact generated by funding.' },
];

const LoginPage = () => {
  const navigate = useNavigate();
  const { loginAs } = useAuth();

  return (
    <div className="min-h-screen bg-mesh-light px-4 py-10">
      <div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.2fr,0.8fr]">
        <section className="rounded-[2rem] bg-slate-950 p-8 text-white shadow-soft lg:p-12">
          <p className="text-xs uppercase tracking-[0.3em] text-sky-200">NGO Education PMS</p>
          <h1 className="mt-6 max-w-2xl font-display text-4xl font-bold leading-tight lg:text-6xl">
            Production-grade prototype for scholarship transparency and student outcomes.
          </h1>
          <p className="mt-6 max-w-xl text-base text-slate-300 lg:text-lg">
            This frontend-only environment is designed to help your team finalize product workflows before backend development. Every module uses realistic mock data, role-based routing, and enterprise-ready interaction patterns.
          </p>

          <div className="mt-10 grid gap-4 md:grid-cols-3">
            {[
              ['Who got the money?', 'Beneficiary coverage, approvals, installments, and program mapping.'],
              ['How was it used?', 'Expense uploads, proof verification, utilization tracking, and audit visibility.'],
              ['What changed?', 'Attendance recovery, academic movement, risk alerts, and impact narratives.'],
            ].map(([title, body]) => (
              <div key={title} className="rounded-3xl border border-white/10 bg-white/5 p-5">
                <p className="text-sm font-semibold text-white">{title}</p>
                <p className="mt-2 text-sm text-slate-300">{body}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-[2rem] border border-white/70 bg-white/90 p-8 shadow-soft">
          <div className="rounded-3xl bg-slate-50 p-5">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-600">Mock Access</p>
            <h2 className="mt-2 font-display text-3xl font-bold text-slate-950">Choose a role to enter the prototype</h2>
            <p className="mt-2 text-sm text-slate-500">Authentication is mocked at this stage so we can focus on product shaping, screen architecture, and stakeholder review.</p>
          </div>

          <div className="mt-6 space-y-3">
            {roles.map((role) => (
              <button
                key={role.key}
                onClick={() => {
                  loginAs(role.key);
                  navigate('/');
                }}
                className="w-full rounded-3xl border border-slate-200 bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-soft"
              >
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-base font-bold text-slate-950">{role.label}</p>
                    <p className="mt-1 text-sm text-slate-500">{role.summary}</p>
                  </div>
                  <span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-semibold text-brand-700">Enter</span>
                </div>
              </button>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
};

export default LoginPage;